CC=g++

OBJS=6rik.o aexp.o bexp.o cexp.o dexp.o eexp.o fexp.o
all: out
	@echo "all"
out: $(OBJS)	
	$(CC) -pg -Wall -I/usr/include -L/usr/local/lib -o out $(OBJS) -lgsl -lgslcblas -lm -O2

6rik.o: 6rik.cpp
	$(CC) -pg -c 6rik.cpp -lm

aexp.o: aexp.cpp
	$(CC) -pg -c aexp.cpp -lm

bexp.o: bexp.cpp
	$(CC) -pg -c bexp.cpp -lm

cexp.o: cexp.cpp
	$(CC) -pg -c cexp.cpp -lm

dexp.o: dexp.cpp
	$(CC) -pg -c dexp.cpp -lm

eexp.o: eexp.cpp
	$(CC) -pg -c eexp.cpp -lm

fexp.o: fexp.cpp
	$(CC) -pg -c fexp.cpp -lm


clean:
	rm -f $(OBJS)		
